# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
